# Generated by Django 5.0.13 on 2025-04-14 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_studentloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterstu1',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
