# Generated by Django 5.0.13 on 2025-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], max_length=10),
        ),
    ]
