# Generated by Django 5.0.13 on 2025-05-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_chatmessage1_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage1',
            new_name='ChatMessagee',
        ),
    ]
