# Generated by Django 5.0.13 on 2025-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_formupload_formrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('original_deadline', models.DateField()),
                ('requested_extension_time', models.IntegerField()),
                ('reason_for_extension', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='extensions/')),
                ('status', models.CharField(choices=[('pending', 'בהמתנה'), ('approved', 'מאושר'), ('rejected', 'נדחה')], default='pending', max_length=20)),
            ],
        ),
    ]
