# Generated by Django 5.0.13 on 2025-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_timeextensionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeextensionrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
