# Generated by Django 5.0.13 on 2025-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_timeextensionrequest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('confirmed', 'מאושר'), ('rejected', 'נדחה')], max_length=20)),
            ],
        ),
    ]
