# Generated by Django 5.0.13 on 2025-05-12 10:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_meeting_meetingslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='אם הפגישה אושרה'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='תאריך ושעה לפגישה'),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office_hours', models.CharField(help_text='שעות קבלה של המרצה', max_length=100)),
                ('email', models.EmailField(help_text='מייל המרצה', max_length=254)),
                ('specialization', models.CharField(help_text='התמחות המרצה', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer'),
        ),
        migrations.DeleteModel(
            name='MeetingSlot',
        ),
    ]
