# Generated by Django 5.2.1 on 2025-05-15 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_officehour_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='office_hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.officehour'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
