# Generated by Django 5.2.1 on 2025-05-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_chatmessage_sender_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('student', 'Student'), ('secretary', 'Secretary')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
