# Generated by Django 5.2.1 on 2025-05-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_professor_studentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrequest',
            name='professor',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='professor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='מייל המרצה'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
