# Generated by Django 5.2.1 on 2025-05-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_studentrequest_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('document_type', models.CharField(choices=[('study_confirmation', 'אישור לימודים'), ('payment_confirmation', 'אישור תשלום'), ('other', 'אחר')], max_length=50)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
