# Generated by Django 5.2.1 on 2025-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_documentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('study_cert', 'אישור לימודים'), ('grade_cert', 'אישור ציונים')], max_length=50),
        ),
    ]
