# Generated by Django 5.2.1 on 2025-05-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_studentprofile1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile1',
            new_name='StuPro',
        ),
    ]
