# Generated by Django 5.2.1 on 2025-05-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_rename_studentprofile1_stupro'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userregisterstu1')),
            ],
        ),
        migrations.DeleteModel(
            name='StuPro',
        ),
    ]
