# Generated by Django 5.2.1 on 2025-06-12 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_receptionhour_receptionbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='נושא')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('time', models.TimeField(verbose_name='שעה')),
                ('location', models.CharField(max_length=200, verbose_name='מיקום')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
            ],
            options={
                'verbose_name': 'שעת קבלה',
                'verbose_name_plural': 'שעות קבלה',
            },
        ),
    ]
