# Generated by Django 5.2.1 on 2025-05-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_receptionhour_receptionbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userregisterstu1'),
        ),
    ]
