# Generated by Django 5.2.1 on 2025-06-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_receptionhour_receptionbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userregisterstu1'),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userregisterlec'),
        ),
    ]
