# Generated by Django 5.2.1 on 2025-05-23 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_meeting_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userregisterlec'),
        ),
    ]
