# Generated by Django 5.2.1 on 2025-06-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_appointment_student_alter_officehour_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionhour',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_hours', to='accounts.userregisterlec'),
        ),
    ]
